### ISSUE TITLE
🐛 <High level mobs in Gusgen>

### ISSUE THREAD

**Issue by Simseru** [TabulaRasa11/TabulaRasa#107]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

High level Madflys exist in gusgen and they aggro, sad face.
## Expected behavior
![img_20220629_234309](https://user-images.githubusercontent.com/59345270/176589716-8ae13314-429e-48e9-832f-3d6b6a394698.png)

**Comment by TabulaRasaXI** [comment]
madflys have been removed.
