### ISSUE TITLE
🐛 <Bonecraft guild shops>

### ISSUE THREAD

**Issue by Simseru** [TabulaRasa11/TabulaRasa#115]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Bonecraft guild shops arn't changing what items they sell when you rank up.  I didnt see any new items at recruit and figured maybe that stuff was just OOE and now at initiate i still dont see any new items. the shop.lua shows the items i was expecting to see so i dunno where the issue is. Someone told me the WW guild was showing whats in the lua so it may just be bone vendors not having it

Both npc's only show the below items and im at initiate rank so should see 2 new sets of items in theory.
![img_20220630_161013](https://user-images.githubusercontent.com/59345270/176769970-31be3347-9e94-4974-95b1-75671afd6edb.png)

**Comment by TabulaRasaXI** [comment]
vendors are limited while we get them audited properly for era accuracy.

**Comment by Simseru** [comment]
Upon further research it seems its era accurate for the BC vendors to be, "bare-bones". TY.
