### ISSUE TITLE
Ochimusha Kote audit request

### ISSUE THREAD

**Issue by Hatberg** [TabulaRasa11/TabulaRasa#135]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Could we audit the droptable for ItemID 14986 Ochimusha Kote ? Server wide we have a very large amount of kills but when asking around zero drops thusfar.

According to https://raw.githubusercontent.com/TabulaRasaXI/TabulaRasa/base/sql/mob_droplist.sql the sum of the grouped rate currently exceeds 1000 as Kote are marked as @UNCOMMON, so possibly this also messes up the drop?

## Expected behavior

Mee Deggi the Punisher should drop Ochimusha Kote, but apparently does not.

**Comment by Judaine** [comment]
Can confirm there is 1 person with Ochimusha Kote currently. I have adjusted the SQL value to be 50 instead of 100 for Ochimusha Kote, so it fits the 1000 itemRate max for a group.
