### ISSUE TITLE
🐛 [Quest] Northward; no reward

### ISSUE THREAD

**Issue by Curlbro** [TabulaRasa11/TabulaRasa#136]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

quest wiki: https://ffxiclopedia.fandom.com/wiki/Northward

## Expected behavior

Reward should be Map of Castle Zvahl, or experience points if the map is already acquired

**Comment by mumencoder** [comment]
The experience/gil is a post-2017 award, this looks like it could be a genuine upstream issue but fixing it would actually be a bug here.
