### ISSUE TITLE
[Bug] Door in Temple of Uggalepih 

### ISSUE THREAD

**Issue by TabulaRasaXI** [TabulaRasa11/TabulaRasa#14]
There is a door at E-8 of map https://github.com/eraffxi/LSB/issues/2 in Temple of Uggalepih that's supposed to require an Uggalepih Key to open from the main hall but not from the other side. Right now, no key is needed.

Reference for the door behavior:
https://ffxiclopedia.fandom.com/wiki/Moon_Reading

**Comment by jefferyrlc** [comment]
Fixed.
