### ISSUE TITLE
Bat Hunt

### ISSUE THREAD

**Issue by Crookesy34** [TabulaRasa11/TabulaRasa#69]
Gate guard is not letting me turn in the Orcish Mail Scales for Bat Hunt.

![Crookesy_2022 06 25_214806](https://user-images.githubusercontent.com/108203240/175796111-e7074acd-3150-494d-94da-5a64052f21df.png)
![Crookesy_2022 06 25_214821](https://user-images.githubusercontent.com/108203240/175796115-f0d14882-4abb-4111-aca0-6dc004232e93.png)

**Comment by mumencoder** [comment]
You have to search the tomb first before you can trade the scales. Once you do this talking to the NPC will give you the message in the attached image.
![searchthetomb](https://user-images.githubusercontent.com/85894709/175810908-159bf838-f77d-44d9-8ad2-ebf3104333fc.png)
