### ISSUE TITLE
🐛 <No EXP loss when under sync>

### ISSUE THREAD

**Issue by Simseru** [TabulaRasa11/TabulaRasa#93]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

When your real level is 31+ and eligible to lose EXP and you die while under the effects of level sync below level 30 you do not lose EXP on death.

Not sure if this is a desired behavior.

**Comment by mumencoder** [comment]
Is this really a bug? https://ffxiclopedia.fandom.com/wiki/Level_Sync "The amount of experience lost when rendered unconscious will be based upon the player's level after Level Sync is in place."

**Comment by Simseru** [comment]
Its really up to the devs, but i would think so. Even if you lose the correct amount of EXP for the reduced level and not your full level, if your jobs true level is over the early game hurdle 31+ then you should lose exp.

That link doesnt really apply as the rules around the exp loss are unique to the server and not era accurate so the devs will have to decide what to do. Protecting EXP below 31 for people who are 31+ will further incentivize purposely doing low level syncs. 

/2centz

**Comment by TabulaRasaXI** [comment]
this is more of a discussion of custom code, Technically it is working as coded right now so a issue with the codebase itself.
